# Generated by Django 6.0.5 on 2026-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('response_json', models.JSONField(help_text='The cached steps JSON response')),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Cache expiration time')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, help_text='SHA-256 hash of submitted code', max_length=64)),
                ('code_snippet', models.TextField(help_text='First 500 chars of submitted code for debugging')),
                ('detected_algorithm', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('source', models.CharField(choices=[('rag_professional', 'RAG + LLM'), ('fallback_local', 'Local Simulation'), ('cached', 'Cache Hit')], default='rag_professional', max_length=32)),
                ('step_count', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0.0, help_text='End-to-end processing time in ms')),
                ('rag_retrieval_ms', models.FloatField(default=0.0, help_text='RAG retrieval time in ms')),
                ('llm_generation_ms', models.FloatField(default=0.0, help_text='LLM generation time in ms')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code_hash', 'created_at'], name='visualizer__code_ha_0c48ff_idx'), models.Index(fields=['detected_algorithm', 'created_at'], name='visualizer__detecte_120b30_idx')],
            },
        ),
    ]
