# Generated by Django 6.0.5 on 2026-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdversaryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('code_snippet', models.TextField(help_text='First 500 chars of submitted code')),
                ('problem_type', models.CharField(default='General DSA', max_length=128)),
                ('feedback', models.TextField(blank=True)),
                ('edge_case_input', models.TextField(blank=True)),
                ('injection_detected', models.BooleanField(default=False)),
                ('vulnerability_count', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('ai_analysis', 'AI Analysis'), ('heuristic', 'Heuristic Fallback'), ('cached', 'Cache Hit')], default='ai_analysis', max_length=32)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Adversary Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedAdversaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('problem_type', models.CharField(max_length=128)),
                ('response_json', models.JSONField()),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
