# Generated by Django 6.0.5 on 2026-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adversary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedadversaryresult',
            name='code_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='cachedadversaryresult',
            unique_together={('code_hash', 'problem_type')},
        ),
    ]
