# Generated by Django 6.0.5 on 2026-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('code_snippet', models.TextField(help_text='First 500 chars of submitted code')),
                ('language', models.CharField(default='cpp', max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('compilation_error', 'Compilation Error'), ('runtime_error', 'Runtime Error'), ('timeout', 'Timeout'), ('security_blocked', 'Security Blocked'), ('mock_success', 'Mock Success')], db_index=True, default='success', max_length=32)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('memory_used_kb', models.IntegerField(default=0)),
                ('security_flags', models.JSONField(blank=True, default=list, help_text='List of security violations detected')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
